Module(body=[
  ImportFrom(
    module='__future__',
    names=[alias(
      name='print_function',
      asname=None)],
    level=0),
  Import(names=[alias(
    name='argparse',
    asname=None)]),
  Import(names=[alias(
    name='torch.nn',
    asname='nn')]),
  Import(names=[alias(
    name='torch.nn.functional',
    asname='F')]),
  Import(names=[alias(
    name='torch.optim',
    asname='optim')]),
  ImportFrom(
    module='torchvision',
    names=[
      alias(
        name='datasets',
        asname=None),
      alias(
        name='transforms',
        asname=None)],
    level=0),
  Import(names=[alias(
    name='torch.utils.data.distributed',
    asname=None)]),
  Import(names=[alias(
    name='horovod.torch',
    asname='hvd')]),
  Assign(
    targets=[Name(
      id='train_dataset',
      ctx=Store())],
    value=Num(n=2)),
  Assign(
    targets=[Name(
      id='batch_size',
      ctx=Store())],
    value=Num(n=2)),
  Assign(
    targets=[Name(
      id='model',
      ctx=Store())],
    value=NameConstant(value=None)),
  Assign(
    targets=[Name(
      id='train_loader',
      ctx=Store())],
    value=Call(
      func=Attribute(
        value=Attribute(
          value=Attribute(
            value=Name(
              id='torch',
              ctx=Load()),
            attr='utils',
            ctx=Load()),
          attr='data',
          ctx=Load()),
        attr='DataLoader',
        ctx=Load()),
      args=[],
      keywords=[
        keyword(
          arg='dataset',
          value=Name(
            id='train_dataset',
            ctx=Load())),
        keyword(
          arg='batch_size',
          value=Name(
            id='batch_size',
            ctx=Load())),
        keyword(
          arg='shuffle',
          value=NameConstant(value=True))])),
  Assign(
    targets=[Name(
      id='test_loader',
      ctx=Store())],
    value=Call(
      func=Attribute(
        value=Attribute(
          value=Attribute(
            value=Name(
              id='torch',
              ctx=Load()),
            attr='utils',
            ctx=Load()),
          attr='data',
          ctx=Load()),
        attr='DataLoader',
        ctx=Load()),
      args=[],
      keywords=[
        keyword(
          arg='dataset',
          value=Name(
            id='test_dataset',
            ctx=Load())),
        keyword(
          arg='batch_size',
          value=Name(
            id='batch_size',
            ctx=Load())),
        keyword(
          arg='shuffle',
          value=NameConstant(value=False))])),
  Assign(
    targets=[Name(
      id='train_sampler',
      ctx=Store())],
    value=Call(
      func=Attribute(
        value=Attribute(
          value=Attribute(
            value=Attribute(
              value=Name(
                id='torch',
                ctx=Load()),
              attr='utils',
              ctx=Load()),
            attr='data',
            ctx=Load()),
          attr='distributed',
          ctx=Load()),
        attr='DistributedSampler',
        ctx=Load()),
      args=[],
      keywords=[
        keyword(
          arg='dataset',
          value=Name(
            id='train_dataset',
            ctx=Load())),
        keyword(
          arg='num_replicas',
          value=Call(
            func=Attribute(
              value=Name(
                id='hvd',
                ctx=Load()),
              attr='size',
              ctx=Load()),
            args=[],
            keywords=[])),
        keyword(
          arg='rank',
          value=Call(
            func=Attribute(
              value=Name(
                id='hvd',
                ctx=Load()),
              attr='rank',
              ctx=Load()),
            args=[],
            keywords=[]))])),
  Assign(
    targets=[Name(
      id='train_loader',
      ctx=Store())],
    value=Call(
      func=Attribute(
        value=Attribute(
          value=Attribute(
            value=Name(
              id='torch',
              ctx=Load()),
            attr='utils',
            ctx=Load()),
          attr='data',
          ctx=Load()),
        attr='DataLoader',
        ctx=Load()),
      args=[],
      keywords=[
        keyword(
          arg='dataset',
          value=Name(
            id='train_dataset',
            ctx=Load())),
        keyword(
          arg='batch_size',
          value=Name(
            id='batch_size',
            ctx=Load())),
        keyword(
          arg='shuffle',
          value=NameConstant(value=True)),
        keyword(
          arg='sampler',
          value=Name(
            id='train_sampler',
            ctx=Load()))])),
  Expr(value=Call(
    func=Attribute(
      value=Name(
        id='hvd',
        ctx=Load()),
      attr='broadcast_parameters',
      ctx=Load()),
    args=[Call(
      func=Attribute(
        value=Name(
          id='model',
          ctx=Load()),
        attr='state_dict',
        ctx=Load()),
      args=[],
      keywords=[])],
    keywords=[keyword(
      arg='root_rank',
      value=Num(n=0))]))])